age=int(input("enter your age\n"))
print("you are " , age , "years old")
print(type(age))
name= input("enter your name\n")
print("your name is " , name)
print(type(name))
weight= float(input("enter your weight\n"))
print("your weight is " , weight)
print(type(weight))